properties:
  title:
    type: string
    maxLength: 60
  description:
    type: string
    maxLength: 160
  keywords:
    type: array
    items:
      type: string
      enum:
        - API Mesh
        - App Builder
        - B2B
        - Cache
        - Cloud
        - Configuration
        - Cron
        - Events
        - Extensibility
        - GraphQL
        - null
        - Observability
        - OpenTelemetry
        - Performance
        - REST
        - Security
        - Starter Kit
        - Tools
        - Upgrade
        - Webhooks

required:
  - title
  - description