%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#FF330F',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#7C0000',
      'lineColor': '#041E2F',
      'secondaryColor': '#006100',
      'tertiaryColor': '#fff'
    }
  }
}%%
flowchart TD
    subgraph Endpoint 
    A[(&nbsp&nbsp&nbspUnified GraphQL&nbsp&nbsp&nbsp \n Endpoint)]
    end
    subgraph &nbspAPI&nbsp&nbspMesh
    B[(&nbsp&nbsp&nbspYour Mesh&nbsp&nbsp&nbsp)]
    end
    subgraph Data  &nbsp Sources
    C[(GraphQL)] 
    D[( REST )] 
    E[( Adobe I/O \n Runtime )] 
    F[(SOAP)]
    G[(Custom API)]
    end

    A --- B
    B --- C
    B --- D
    B --- E
    B --- F
    B --- G