flowchart LR
    subgraph Box1[Adobe Commerce]
        A1[New Order] --> A2[I/O Events to Adobe Commerce]
        A3[AC Extenstion that adds custom data to GQL or custom calcultations] --> A4[GQL]
    end
    subgraph Box2[Order Export Service]
        B1[Transformation]
    end
    A4 --> Box2 --> Box3[Order Management System]
    A2 --> Box2